version: '3.8'

services:

  mysql_db:
    build: ./database
    container_name: mysql_db
    ports:
      - "3380:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  api:
    build: ./backend
    container_name: flask_api
    ports:
      - "5000"
    links:
      - mysql_db
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./frontend/dist:/app:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge